import { Question } from "@/components/HandwritingCanvas";

export const grade1: Question[] = [
  // grade1_1 数の訓読み（①〜⑩）
  { text: "〇つ", ruby: ["ひと"], correct: ["一"] },
  { text: "〇つ", ruby: ["ふた"], correct: ["二"] },
  { text: "〇つ", ruby: ["みっ"], correct: ["三"] },
  { text: "〇つ", ruby: ["よっ"], correct: ["四"] },
  { text: "〇つ", ruby: ["いつ"], correct: ["五"] },
  { text: "〇つ", ruby: ["むっ"], correct: ["六"] },
  { text: "〇つ", ruby: ["なな"], correct: ["七"] },
  { text: "〇つ", ruby: ["やっ"], correct: ["八"] },
  { text: "〇つ", ruby: ["ここの"], correct: ["九"] },
  { text: "〇", ruby: ["とお"], correct: ["十"] },
  // grade1_1 月名（⑪〜⑳）
  { text: "〇月", ruby: ["いち"], correct: ["一"] },
  { text: "〇月", ruby: ["に"], correct: ["二"] },
  { text: "〇月", ruby: ["さん"], correct: ["三"] },
  { text: "〇月", ruby: ["し"], correct: ["四"] },
  { text: "〇月", ruby: ["ご"], correct: ["五"] },
  { text: "〇月", ruby: ["ろく"], correct: ["六"] },
  { text: "〇月", ruby: ["しち"], correct: ["七"] },
  { text: "〇月", ruby: ["はち"], correct: ["八"] },
  { text: "〇月", ruby: ["く"], correct: ["九"] },
  { text: "〇月", ruby: ["じゅう"], correct: ["十"] },
  // grade1_1 数のかん字を使った文（㉑〜㉚）
  { text: "〇月", ruby: ["ひと"], correct: ["一"] },
  { text: "〇とおり", ruby: ["ふた"], correct: ["二"] },
  { text: "〇日月", ruby: ["み"], correct: ["三"] },
  { text: "〇回目", ruby: ["よん"], correct: ["四"] },
  { text: "〇月", ruby: ["ここの"], correct: ["九"] },
  { text: "〇日", ruby: ["ここの"], correct: ["九"] },
  { text: "〇てん", ruby: ["ひゃく"], correct: ["百"] },
  { text: "〇さつの本", ruby: ["きゅう"], correct: ["九"] },
  { text: "〇本のペン", ruby: ["じゅっ"], correct: ["十"] },
  { text: "〇えざくら", ruby: ["や"], correct: ["八"] },
  // grade1_1 数のかん字を使った文（㉛〜㊵）
  { text: "〇いろのにじ", ruby: ["なな"], correct: ["七"] },
  { text: "〇人", ruby: ["じゅう"], correct: ["十"] },
  { text: "生まれて〇月め", ruby: ["む"], correct: ["六"] },
  { text: "〇円さつ", ruby: ["せん"], correct: ["千"] },
  { text: "〇人", ruby: ["ひと"], correct: ["一"] },
  { text: "〇人", ruby: ["ふた"], correct: ["二"] },
  { text: "〇日", ruby: ["つい"], correct: ["一"] },
  { text: "〇日", ruby: ["ふつ"], correct: ["二"] },
  { text: "〇〇", ruby: ["たなばた"], correct: ["七夕"] },
  { text: "〇よがみ", ruby: ["ち"], correct: ["千"] },
  // grade1_2 曜日のかん字（①〜⑩）
  { text: "〇ようび", ruby: ["にち"], correct: ["日"] },
  { text: "〇ようび", ruby: ["げつ"], correct: ["月"] },
  { text: "〇ようび", ruby: ["か"], correct: ["火"] },
  { text: "〇ようび", ruby: ["すい"], correct: ["水"] },
  { text: "〇ようび", ruby: ["もく"], correct: ["木"] },
  { text: "〇ようび", ruby: ["きん"], correct: ["金"] },
  { text: "〇ようび", ruby: ["ど"], correct: ["土"] },
  { text: "〇なた", ruby: ["ひ"], correct: ["日"] },
  { text: "〇月〇日", ruby: ["さん", "みっ"], correct: ["三", "三"] },
  { text: "お〇さま", ruby: ["つき"], correct: ["月"] },
  // grade1_2 曜日のかん字（⑪〜⑳）
  { text: "〇をけす", ruby: ["ひ"], correct: ["火"] },
  { text: "〇山", ruby: ["か"], correct: ["火"] },
  { text: "〇どう", ruby: ["すい"], correct: ["水"] },
  { text: "〇をのむ", ruby: ["みず"], correct: ["水"] },
  { text: "りんごの〇", ruby: ["き"], correct: ["木"] },
  { text: "お〇", ruby: ["かね"], correct: ["金"] },
  { text: "〇いろ", ruby: ["きん"], correct: ["金"] },
  { text: "ねん〇", ruby: ["ど"], correct: ["土"] },
  { text: "〇けむり", ruby: ["つち"], correct: ["土"] },
  { text: "お〇さま", ruby: ["ひ"], correct: ["日"] },
  // grade1_3 自然のかん字（①〜⑩）
  { text: "〇のぼり", ruby: ["やま"], correct: ["山"] },
  { text: "ふじ〇", ruby: ["さん"], correct: ["山"] },
  { text: "〇のながれ", ruby: ["かわ"], correct: ["川"] },
  { text: "お〇であそぶ", ruby: ["がわ"], correct: ["川"] },
  { text: "小〇をひろう", ruby: ["いし"], correct: ["石"] },
  { text: "じ〇", ruby: ["しゃく"], correct: ["石"] },
  { text: "〇き", ruby: ["くう"], correct: ["空"] },
  { text: "青い〇", ruby: ["そら"], correct: ["空"] },
  { text: "〇っぽのはこ", ruby: ["から"], correct: ["空"] },
  { text: "へやが〇く", ruby: ["あ"], correct: ["空"] },
  // grade1_3 自然のかん字（⑪〜⑲）
  { text: "せきを〇ける", ruby: ["あ"], correct: ["空"] },
  { text: "〇やけの空", ruby: ["ゆう"], correct: ["夕"] },
  { text: "〇だちにあう", ruby: ["ゆう"], correct: ["夕"] },
  { text: "へやの〇じょう", ruby: ["てん"], correct: ["天"] },
  { text: "うつくしいほう〇", ruby: ["せき"], correct: ["石"] },
  { text: "あしたの〇きよほうは〇だ。", ruby: ["てん", "あめ"], correct: ["天", "雨"] },
  { text: "〇〇のばあいはちゅうしです", ruby: ["うてん"], correct: ["雨天"] },
  { text: "〇のがわ", ruby: ["あま"], correct: ["天"] },
  { text: "〇やどり", ruby: ["あま"], correct: ["雨"] },
  // grade1_4 様子のかん字 大・中・小（①〜⑨）
  { text: "〇きい犬", ruby: ["おお"], correct: ["大"] },
  { text: "〇雨", ruby: ["おお"], correct: ["大"] },
  { text: "〇すきな人", ruby: ["おお"], correct: ["大"] },
  { text: "〇へんだ", ruby: ["だい"], correct: ["大"] },
  { text: "かばんの〇", ruby: ["なか"], correct: ["中"] },
  { text: "〇学校", ruby: ["しょう"], correct: ["小"] },
  { text: "〇石", ruby: ["こ"], correct: ["小"] },
  { text: "〇川", ruby: ["お"], correct: ["小"] },
  { text: "〇さいむし", ruby: ["ちい"], correct: ["小"] },
  // grade1_4 様子のかん字 左・白・青・赤・円（①〜⑨）
  { text: "〇足", ruby: ["ひだり"], correct: ["左"] },
  { text: "まっ〇いゆき", ruby: ["しろ"], correct: ["白"] },
  { text: "〇い海", ruby: ["あお"], correct: ["青"] },
  { text: "〇年", ruby: ["せい"], correct: ["青"] },
  { text: "〇しんごう", ruby: ["あお"], correct: ["青"] },
  { text: "〇とんぼ", ruby: ["あか"], correct: ["赤"] },
  { text: "〇い花", ruby: ["あか"], correct: ["赤"] },
  { text: "十〇玉", ruby: ["えん"], correct: ["円"] },
  { text: "〇いテーブル", ruby: ["まる"], correct: ["円"] },
  // grade1_4 様子のかん字 円・正・音・早・上・下（①〜⑨）
  { text: "空とぶ〇ばん", ruby: ["えん"], correct: ["円"] },
  { text: "〇かい", ruby: ["せい"], correct: ["正"] },
  { text: "〇しいこたえ", ruby: ["ただ"], correct: ["正"] },
  { text: "むしの〇", ruby: ["おと"], correct: ["音"] },
  { text: "〇がく", ruby: ["おん"], correct: ["音"] },
  { text: "〇くおきる", ruby: ["はや"], correct: ["早"] },
  { text: "しせいを〇す", ruby: ["ただ"], correct: ["正"] },
  { text: "本だなの〇", ruby: ["うえ"], correct: ["上"] },
  { text: "つくえの〇", ruby: ["した"], correct: ["下"] },
  // grade1_5（前半10問）上・下・赤・早の動詞
  { text: "あたまを〇げる", ruby: ["あ"], correct: ["上"] },
  { text: "かいだんを〇がる", ruby: ["あ"], correct: ["上"] },
  { text: "さかを〇る", ruby: ["のぼ"], correct: ["上"] },
  { text: "おんどを〇げる", ruby: ["さ"], correct: ["下"] },
  { text: "ねだんが〇がる", ruby: ["さ"], correct: ["下"] },
  { text: "山を〇りる", ruby: ["お"], correct: ["下"] },
  { text: "手を〇ろす", ruby: ["お"], correct: ["下"] },
  { text: "かおを〇らめる", ruby: ["あか"], correct: ["赤"] },
  { text: "しゅっぱつが〇まる", ruby: ["はや"], correct: ["早"] },
  { text: "よていを〇める", ruby: ["はや"], correct: ["早"] },
  // grade1_5（後半7問）上下・川上・川下など
  { text: "〇ぎをきる", ruby: ["うわ"], correct: ["上"] },
  { text: "〇〇", ruby: ["じょうげ"], correct: ["上下"] },
  { text: "〇〇", ruby: ["かわかみ"], correct: ["川上"] },
  { text: "〇〇", ruby: ["かわしも"], correct: ["川下"] },
  { text: "〇じき", ruby: ["しょう"], correct: ["正"] },
  { text: "てがみを〇さい", ruby: ["くだ"], correct: ["下"] },
  { text: "さかを〇る", ruby: ["くだ"], correct: ["下"] },
  // grade1_6 動物・植物のかん字 上段（①〜⑩）
  { text: "ほたて〇", ruby: ["がい"], correct: ["貝"] },
  { text: "〇のさんぽ", ruby: ["いぬ"], correct: ["犬"] },
  { text: "もうどう〇", ruby: ["けん"], correct: ["犬"] },
  { text: "〇とりあみ", ruby: ["むし"], correct: ["虫"] },
  { text: "こん〇", ruby: ["ちゅう"], correct: ["虫"] },
  { text: "〇びんに〇を〇ける。", ruby: ["か", "はな", "い"], correct: ["花", "花", "生"] },
  { text: "〇うま", ruby: ["たけ"], correct: ["竹"] },
  { text: "人気を〇む", ruby: ["う"], correct: ["生"] },
  { text: "〇まれた日", ruby: ["う"], correct: ["生"] },
  { text: "〇きもの", ruby: ["い"], correct: ["生"] },
  { text: "先〇", ruby: ["せい"], correct: ["生"] },
  // grade1_6 動物・植物のかん字 下段（①〜⑪）
  { text: "〇やさい", ruby: ["なま"], correct: ["生"] },
  { text: "〇むしり", ruby: ["くさ"], correct: ["草"] },
  { text: "〇の中", ruby: ["はやし"], correct: ["林"] },
  { text: "〇の〇〇", ruby: ["もり", "くさばな"], correct: ["森", "草花"] },
  { text: "一年〇", ruby: ["せい"], correct: ["生"] },
  { text: "はが〇える", ruby: ["は"], correct: ["生"] },
  { text: "〇わ", ruby: ["ちく"], correct: ["竹"] },
  { text: "〇んぼ", ruby: ["た"], correct: ["田"] },
  { text: "ざっ〇", ruby: ["そう"], correct: ["草"] },
  { text: "〇〇", ruby: ["しんりん"], correct: ["森林"] },
  { text: "〇〇", ruby: ["すいでん"], correct: ["水田"] },
  // grade1_7 動作のかん字（①〜⑩）
  { text: "左右を〇る", ruby: ["み"], correct: ["見"] },
  { text: "本を〇せる", ruby: ["み"], correct: ["見"] },
  { text: "〇学する", ruby: ["けん"], correct: ["見"] },
  { text: "いすから〇つ", ruby: ["た"], correct: ["立"] },
  { text: "はたを〇てる", ruby: ["た"], correct: ["立"] },
  { text: "ゆっくり〇む", ruby: ["やす"], correct: ["休"] },
  { text: "手を〇める", ruby: ["やす"], correct: ["休"] },
  { text: "〇けいする", ruby: ["きゅう"], correct: ["休"] },
  { text: "へやに〇る", ruby: ["はい"], correct: ["入"] },
  { text: "〇りぐち", ruby: ["い"], correct: ["入"] },
  // grade1_7 動作のかん字（⑪〜⑯）
  { text: "はこに〇れる", ruby: ["い"], correct: ["入"] },
  { text: "〇学しき", ruby: ["にゅう"], correct: ["入"] },
  { text: "てがみを〇す", ruby: ["だ"], correct: ["出"] },
  { text: "みせを〇る", ruby: ["で"], correct: ["出"] },
  { text: "たいかいに〇〇する", ruby: ["しゅっ", "じょう"], correct: ["出", "場"] },
  { text: "き〇する", ruby: ["りっ"], correct: ["立"] },
  // grade1_8 体のかん字（①〜⑩）
  { text: "〇ぶえ", ruby: ["くち"], correct: ["口"] },
  { text: "〇さしゆび", ruby: ["ひと"], correct: ["人"] },
  { text: "がいこく〇", ruby: ["じん"], correct: ["人"] },
  { text: "三〇", ruby: ["にん"], correct: ["人"] },
  { text: "〇と〇", ruby: ["て", "あし"], correct: ["手", "足"] },
  { text: "あく〇", ruby: ["しゅ"], correct: ["手"] },
  { text: "〇と〇", ruby: ["め", "みみ"], correct: ["目", "耳"] },
  { text: "〇がはやい", ruby: ["あし"], correct: ["足"] },
  { text: "〇ども", ruby: ["こ"], correct: ["子"] },
  { text: "〇と〇", ruby: ["おとこ", "おんな"], correct: ["男", "女"] },
  // grade1_8 体のかん字（⑪〜⑰）
  { text: "〇〇", ruby: ["だんし"], correct: ["男子"] },
  { text: "〇さま", ruby: ["おう"], correct: ["王"] },
  { text: "〇〇のおおいまち", ruby: ["じんこう"], correct: ["人口"] },
  { text: "〇〇ようのおてあらい", ruby: ["じょし"], correct: ["女子"] },
  { text: "〇ひょうをたてる", ruby: ["もく"], correct: ["目"] },
  { text: "おかねが〇りない", ruby: ["た"], correct: ["足"] },
  { text: "〇〇のくつ", ruby: ["いっそく"], correct: ["一足"] },
  // grade1_9 学校のかん字（①〜⑩）
  { text: "じどう〇", ruby: ["しゃ"], correct: ["車"] },
  { text: "〇にのる", ruby: ["くるま"], correct: ["車"] },
  { text: "〇をかく", ruby: ["ぶん"], correct: ["文"] },
  { text: "ちゅう〇する", ruby: ["もん"], correct: ["文"] },
  { text: "〇をかく", ruby: ["じ"], correct: ["字"] },
  { text: "〇をよむ", ruby: ["ほん"], correct: ["本"] },
  { text: "〇まえ", ruby: ["な"], correct: ["名"] },
  { text: "〇〇", ruby: ["めいじん"], correct: ["名人"] },
  { text: "〇もち", ruby: ["ちから"], correct: ["力"] },
  { text: "〇〇", ruby: ["がっこう"], correct: ["学校"] },
  // grade1_9 学校のかん字（⑪〜⑳）
  { text: "字を〇ぶ", ruby: ["まな"], correct: ["学"] },
  { text: "〇〇", ruby: ["せんせい"], correct: ["先生"] },
  { text: "〇にいく", ruby: ["さき"], correct: ["先"] },
  { text: "はりと〇", ruby: ["いと"], correct: ["糸"] },
  { text: "〇〇", ruby: ["くうき"], correct: ["空気"] },
  { text: "〇をつける", ruby: ["き"], correct: ["気"] },
  { text: "〇の人", ruby: ["むら"], correct: ["村"] },
  { text: "〇にいく", ruby: ["まち"], correct: ["町"] },
  { text: "〇〇", ruby: ["みょうじ"], correct: ["名字"] },
  { text: "〇〇", ruby: ["さんそん"], correct: ["山村"] },
  // grade1_9 学校のかん字（㉑〜㉓）
  { text: "〇ないかい", ruby: ["ちょう"], correct: ["町"] },
  { text: "〇〇", ruby: ["たいりょく"], correct: ["体力"] },
  { text: "かい〇", ruby: ["りき"], correct: ["力"] },
];
